MAINT, TST: Remove nose imports and use pytest
QuantEcon/QuantEcon.py pull request #610
Opened 2022-03-11 12:55 UTC by Smit-create

cc @mmcky

2022-03-13 18:04 UTC, oyamad requested changes
@Smit-create Thanks! I have a few comments.

2022-03-14 10:05 UTC, pep8speaks commented
Hello @Smit-create! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`quantecon/markov/tests/test_gth_solve.py`](https://github.com/QuantEcon/QuantEcon.py/blob/7f3975791398e7234b0a958d322d5fde3e39852b/quantecon/markov/tests/test_gth_solve.py):

> [Line 7:29](https://github.com/QuantEcon/QuantEcon.py/blob/7f3975791398e7234b0a958d322d5fde3e39852b/quantecon/markov/tests/test_gth_solve.py#L7): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2022-03-14 12:15 UTC, oyamad approved these changes
Thanks! All look good to me.

2022-03-14 23:51 UTC, mmcky commented
thanks @oyamad and @Smit-create.

2022-03-14 23:51 UTC, merged