RELEASE: Setup for v0.7.0
QuantEcon/QuantEcon.py pull request #696
Opened 2023-02-24 05:57 UTC by mmcky

@oyamad tried to get the balance right re: listing the fixes and maintenance in a concise way while highlight the main fixes.

2023-02-24 11:43 UTC, oyamad requested changes
@mmcky Could you please also include #690 (which implements a Numba-jitted linear complementarity problem (LCP) solver based on Lemke's algorithm).

2023-02-24 11:46 UTC, oyamad commented on CHANGELOG.md
> +There were a range of additional maitenance and fixes including [Update __Iss.py - Remove broken link](https://github.com/QuantEcon/QuantEcon.py/pull/692), [693](https://github.com/QuantEcon/QuantEco
This `[MAINT: Import from _graph_tools, _gridtools](https://github.com/QuantEcon/QuantEcon.py/pull/683)` is just a leftover from #682; it doesn't have to be included here.

2023-02-24 11:46 UTC, oyamad commented on CHANGELOG.md
> +2. [ENH: Adding Discrete Approximation of VAR Methods](https://github.com/QuantEcon/QuantEcon.py/pull/640) ([crondonm](https://github.com/crondonm)) which is a routine based on the work `Finite-State
I don't know how much we based our implementation on their work.

2023-03-06 05:44 UTC, mmcky commented
thanks @oyamad made those updates and changes

2023-03-06 09:24 UTC, oyamad commented on CHANGELOG.md
> +Thank you to ([bensonarafat](https://github.com/bensonarafat)), ([crondonm])(https://github.com/crondonm)), ([oyamad](https://github.com/oyamad)), ([jstac](https://github.com/jstac)), and ([Smit-crea
```suggestion
Thank you to ([bensonarafat](https://github.com/bensonarafat)), ([crondonm](https://github.com/crondonm)), ([oyamad](https://github.com/oyamad)), ([jstac](https://github.com/jstac)), and ([Smit-create](https://github.com/Smit-create)) for all your contributions, PR reviews, and comments. 
```

2023-04-08 06:40 UTC, oyamad approved these changes
@mmcky I think it is ready to tag a new release. Thanks!

2023-04-16 04:05 UTC, oyamad commented
Updated CHANGELOG.md and rebased on the latest `main`.

2023-04-24 00:43 UTC, merged